################################## common options ######################################
server:
  port: 30010
debug: true
spring:
  application:
    name: zodiac-cloud-registration
  profiles:
    active: dev
# 日志
logging:
  level:
    root: info
  file: logs/${spring.application.name}.log
# https://blog.asarkar.org/technical/netflix-eureka/
eureka:
  # EurekaServerConfigBean
  server:
    # 关闭自我保护
    enable-self-preservation: false
    # 续期时间(主动失效监测间隔)
    eviction-interval-timer-in-ms: 30000
    # 禁用 readOnlyCacheMap 已经有了 readWriterCacheMap
    use-read-only-response-cache: false
  # EurekaInstanceConfigBean
  instance:
    hostname: registration
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  # EurekaClientConfigBean
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

################################## profile options ######################################
---
spring:
  profiles: dev

################################## profile options ######################################
---
spring:
  profiles: test

################################## profile options ######################################
---
spring:
  profiles: prod