########################################
debug: true
server:
  port: 9999
# spring
spring:
  profiles:
    active: dev
  application:
    name: zodiac-app-gsps
  # message
  messages:
    basename: i18n/messages,i18n/validation/messages
    encoding: UTF-8
# log
logging:
  root: info
  com.zodiac.app: debug
  com.github.lzm320a99981e: debug
  file: logs/${spring.application.name}.log
# swagger
swagger:
  base-package: com.zodiac.app
  base-path: /**
  exclude-path: /error
########################################
quickly:
  starter:
    token:
      base64-encoded-secret-key: 66668888
      expires-in: 30
      refresh-expires-in: 7200
    storage:
      classification-map:
        100101: 'personal'
        100201: 'expert'