################################## common options ######################################
server:
  port: 30020
# spring
spring:
  profiles:
    active: dev
  application:
    name: zodiac-cloud-shared
  # 国际化
  messages:
    basename: i18n/messages,i18n/validation/messages
    encoding: UTF-8
# log
logging:
  level:
    com.github.lzm320a99981e: debug
  file: logs/${spring.application.name}.log
# swagger
swagger:
  base-package: com.github.lzm320a99981e.cloud.shared
  base-path: /**
  exclude-path: /error
# eureka
eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    # 心跳间隔
    lease-renewal-interval-in-seconds: 30
    # 心跳过期
    lease-expiration-duration-in-seconds: 90
  client:
    # 向服务端注册
    fetch-registry: true
    # 刷新依赖的服务列表
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: http://registration:30010/eureka/
ribbon:
  # 处理超时时间
  ConnectTimeout: 10000
  # 连接超时时间
  ReadTimeout: 10000
  # 负载时的实例缓存
  ServerListRefreshInterval: 20000

# 自定义
customize:
  # 令牌
  token:
    base64-encoded-secret-key: 12345678
    expires-in: 7200
    refresh-expires-in: 720000
  filter-interceptor-api:
    enabled: true
    url-patterns: ['/**']

################################## profile options ######################################
---
spring:
  profiles: dev
################################## profile options ######################################
---
spring:
  profiles: test
################################## profile options ######################################
---
debug: false
spring:
  profiles: prod